### ISSUE TITLE
Support Nested structs

### ISSUE THREAD

**Issue by andrewbradnan** [JosephDuffy/HashableMacro#12]
If you have
```
@Hashable struct Parent {
     
     @Hashable struct Child {
     }
}

```

it generates
```
extension Parent.Child {
    static func ==(lhs: Child, rhs: Child) -> Bool <----- Cannot find 'Child' in scope.
}
```

namedDeclaration.name.text is not the fully qualified name.  Hopefully you know how to grab it.  SwiftSyntax is new to me.

Thanks

**Comment by JosephDuffy** [comment]
Thanks, I'll look in to this! My guess is that the macro doesn't get enough context to know this, but it may get enough to know when it can use `Self`, which would fix this for some situations.

**Comment by JosephDuffy** [comment]
`Self` works for structs so I've updated _all_ structs to use `Self` in https://github.com/JosephDuffy/HashableMacro/pull/15. For classes you can provide a `fullyQualifiedName` parameter. It's not ideal but at this this usecase is now possible!
